spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: '{cipher}AQBrS2d/xlqwkiueF8rwzpSWWlxfvQy+3yhaS0vY445Wpt8lgqImtvqggWP2AvJxi9EJDvLf3pPjn2j7+V64fr4kNQUxHycEWDSGFfGCt81yhg8jVaT8COtbu3F5il1CLmBpVnZUpRNKc63h8cHmr+eB963reQ4DqZ9loGN7yUz7omAvjKxQ8B6oB+UHQ9eDIdlo/9QJTJHFFsozxw3t8mQXDn76iYJepn9kxCyPK/UTzGJa/nYZ9mvYiBcC8w6bi2+TwOjr3/t4mplQYP1BAWERy3ltGceKoKtEHya5zidc1zamS3EtcnfCTYhD5hD9FhOAQw4G94F/RzEbMHz/MleO5uKeMmONUlOE0XYEH3Yr1Adbhd+fdZXxXOL+HVR2dsA='
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

token:
  expiration_time: 86400000
  secret: '{cipher}AQAvCwjQai3fShIwneoaRW1uOC9YBS+ZridOg3CsUvNxgN6b6zqy7M7k6eT4Gi4K0J5FSGLOT6nusD7olzgqsg8StZaGxYECO9xih2Bn/ojfTGjULcCJj2OB/zwEyivIHMsZ7AL4AKqy48cnJ5SNstRhBpxcNkiamwBDggWc32MTq0aQLEJ+5cpOcbTB7L2xASMXC37nz69hnP8e+mIR2rh2z4Cem/r1+yX4rnRfZGhs+TiqMpEAvLQOp0bPowGBz34/FdT2Gu6Y0Ag/A1zCUWkdRsNAW1D6/TYnyKEiHxdzP8Vg1rZKxv5fvfX151oKOQf+N9NVdKGdt1YCtwpXo3RkWZEL8OVG4q/Zw5yG/7C05d+M4FfDYJm5phXOg2cWYrnAYILz0LjUfrxS4E1rTL1WxT5SgVLRW5iqQnWxgAAIti4zS6rVgfvOuPSsFqv6Akc='

order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders